######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

cd "/nfs/home/a/ay_vashi/COEN_317/lab_3/lab_3_plan_ahead_part_2/lab_3_plan_ahead_part_2.srcs/sources_1/edk/system_part_2"
if { [xload new system_part_2.xmp] != 0 } {
  exit -1
}
xset arch zynq
xset dev xc7z020
xset package clg484
xset speedgrade -1

xset binfo ZC702

if { [xset hier sub] != 0 } {
  exit -1
}
xset hdl vhdl
save proj
exit
