######################################################
#
# XPS Tcl API script generated by PlanAhead
#
######################################################

proc _main_ {} {
  cd "/nfs/home/a/ay_vashi/COEN_317/lab_3/lab_3_plan_ahead_part_2/lab_3_plan_ahead_part_2.srcs/sources_1/edk/system_2_part_2_final"
  if { [ catch {xload xmp system_2_part_2_final.xmp} result ] } {
    exit 10
  }
  # Set the export bmm/bit 0
  xset sdk_export_bmm_bit 0
  # Set the export dir
  xset sdk_export_dir /nfs/home/a/ay_vashi/COEN_317/lab_3/lab_3_plan_ahead_part_2/lab_3_plan_ahead_part_2.sdk/SDK/SDK_Export
  if { [catch {run exporttosdk} result] } {
    return -1
  }
  return $result
}

# Export Hardware Data
if { [catch {_main_} result] } {
  exit -1
}

# Check return status and exit
if { [string length $result] == 0 } {
  exit 0
} else {
  exit $result
}
